### ISSUE TITLE
abstract methods in GenBase and generating declaration files

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#12]
This is just a note...
I'm looking at writing a TypeScript declaration file generator.

I noticed that `GenBase` has a bunch of abstract methods like `WriteNewArray`, `WriteListStorageInit`, `WriteCall` etc.  Since TypeScript declaration files don't contain method implementations, a `GenTsDecls` class would have to implement these methods as no-ops.  Not a huge deal, but what do you think, should we extract an interface from `GenBase` so that `GenTsDecls` and anything like it (I also use Flowtype for some JS projects 🙃) doesn't have to implement a bunch of irrelevant abstract methods?

**Comment by jedwards1211** [comment]
Actually nevermind.  I might as well just leave stubs that throw `NotImplementedException` in case we decide to implement full TS source code generation in the future.

**Comment by pfusik** [comment]
Yes, `throw new NotImplementedException()` is the way to go.

**Comment by jedwards1211** [comment]
actually I ended up just inheriting `GenJs` for now, so that I can share some of the code for identifier case and so that I can output the correct enum value initializers.
