### ISSUE TITLE
[GenJs] still expects 2 arguments to list.Insert

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#15]
`GenCpp` allows the second argument to be optional:

```c#
		else if (obj.Type is CiListType list2 && method.Name == "Insert") {
			if (method.Parameters.Count == 1) {
```

`GenJs` doesn't:
```c#
		else if (obj.Type is CiListType && method.Name == "Insert") {
			obj.Accept(this, CiPriority.Primary);
			Write(".splice(");
			args[0].Accept(this, CiPriority.Statement);
			Write(", 0, ");
			args[1].Accept(this, CiPriority.Statement);
			Write(')');
```
Also it's not documented what it means to omit the second argument.

`LibListObjectStg.ci` calls with one argument:

```c#
		Test! u = list.Insert(0);
```
I'm getting an array index out of bounds error because of this when I try to test `LibListObjectStg.ci` on JS or TS.

**Comment by pfusik** [comment]
> it's not documented what it means to omit the second argument.

[Collections](../../blob/master/ci.md):

> Object or array *storage* must be added/inserted without specifying the value.

It isn't implemented in many of the backends yet.

**Comment by pfusik** [comment]
Implemented. Also, eliminated returning a reference to the added/inserted storage.

**Comment by jedwards1211** [comment]
Oh makes sense, I think I didn't have the latest version of `ci.md`.  Thanks!
