### ISSUE TITLE
[GenJs] Outputs Object.entries, which isn't available in ES5

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#16]
https://github.com/pfusik/cito/blob/master/GenJs.cs#L671

`Object.entries` is from the 2017 version of ECMAScript.  We should iterate over `Object.keys` instead and get the corresponding value inside the loop.

We could run the generated code through [`eslint`](https://eslint.org/) to ensure that it's valid ES5 (or a later version that we choose).  I could make a PR for that

**Comment by pfusik** [comment]
What's the market share of the different JS versions?

**Comment by jedwards1211** [comment]
Yes most up-to-date browsers and recent versions of Node have almost all new features implemented.  Here's another good site that shows what features are available in various versions of browsers and node: https://kangax.github.io/compat-table/es6/

I don't know if there's a market share table by JS version/features but [this site says 5% of people are still using IE11](https://netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browserVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222019-10%22%2C%22dateEnd%22%3A%222020-09%22%2C%22segments%22%3A%22-1000%22%7D).  And IE11 doesn't support many ES6 features.

Since we have Babel, a great transpiler that can transpile modern JS code to run on much older environments, we certainly don't have to output pure ES5.  But it would have to be called as a second step after cito for people who want to target old versions of JS.  It would just be good to be specific about what version we're targeting.

**Comment by pfusik** [comment]
In early versions of `cito` I made a mistake of supporting old language standards such as C89 and Perl 5.8. This seemed reasonable at that time (the Microsoft compiler didn't support C99 back then). In retrospect, it was a waste of my time. Now I do the opposite: some C++ translations depend on C++20 which isn't fully implemented in Clang or GCC, but I expect it to be sooner or later.

IE is [phased out](https://en.wikipedia.org/wiki/Internet_Explorer#End_of_life) by Microsoft itself, so I don't feel like supporting it. What's your opinion?

**Comment by pfusik** [comment]
`cito` also targeted Flash Player's ActionScript at some point.

**Comment by jedwards1211** [comment]
I see, I'm fine with not supporting old versions of JS as long as we document it and include some basic instructions on transpiling the generated JS to older versions with Babel.

I think we should make a table of what features don't work in target languages/versions, since I started running the tests on generated ts I noticed how many // FAIL comments there are for specific langs.

I noticed the other day that someone wants to implement a translator for Perl 6 aka Raku 🙃: https://news.perlfoundation.org/post/grant_proposal_cito_to_raku_translator

**Comment by jedwards1211** [comment]
Oh I see that you already commented on that post.  I guess you made the proposal?  Since it was posted by some other guy I thought someone else was proposing it.  $8192 for implementing a translator would be pretty sweet deal!

**Comment by pfusik** [comment]
First on my priority list is having proper error messages for features that aren't supported in the target language, instead of the ugly stacktraces or generating code that doesn't compile.

Yes, I wrote the Raku grant proposal myself. I was mostly interested in the opinion of the Raku community and I'm satisfied with the comments I got.

**Comment by pfusik** [comment]
I'm not going to implement IE compatibility. Microsoft is killing it. [Wikipedia](https://en.wikipedia.org/wiki/Internet_Explorer) says IE's market share is 0.58%. And it will only decrease.
