### ISSUE TITLE
[GenJs] padStart, padEnd aren't available in ES5

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#17]
One way you can check which version an API was added in is to look it up in devdocs (e.g. https://devdocs.io/javascript/global_objects/string/padstart) and scroll to the specifications section.  If it's ES5 you should see ECMAScript 5.1 listed in the specifications.

We could also consider targeting a later version of JS.

**Comment by pfusik** [comment]
This doesn't look like a serious compatibility issue: https://caniuse.com/?search=padStart
We discussed IE in #16.
