### ISSUE TITLE
[GenJs] prefer triple-equals ===

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#18]
I think a lot of JS programmers intentionally avoid `==` since its behavior is fairly complicated when any coercion is involved.  The one exception is `x == null` is `true` if `x` is `null` or `undefined`, which is useful enough.  `===` doesn't do any coercion and would work just fine since we're coming from strongly-typed code anyway.

**Comment by pfusik** [comment]
I had been thinking of it and didn't find advantages. An obvious disadvantage is slightly longer code.
The Ć code is type-checked and there's never a comparison between e.g. a number and a string or a number and a boolean.
Of course, the user of the library could break type safety, but that could break the code in a thousand ways and I don't think the kind of equality operator can help.

Could you give examples how it would help?

**Comment by jedwards1211** [comment]
I guess there wouldn't be any concrete advantages, I just have a habitual bias against double equals 😁

Theoretically `===` is a bit faster (https://stackoverflow.com/questions/12374815/javascript-vs-operators-performance) but the difference is pretty negligible, especially when no coercion needs to be done.
