### ISSUE TITLE
Extracting helper functions in generators

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#19]
I was looking into implementing `Regex.Escape` for JS/TS.  Even though it's pretty simple (`string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&')`) I think it would be better to write a `regexEscape` helper function at the top of the file and then call it.

I haven't noticed evidence that `GenJs` currently does this for anything else...I think a generic mechanism to extract helper functions would be useful in a lot of situations.

This would make the rest of the translation simple to write:

```c#
Write(regexEscapeMethodName + '(');
pattern.Accept(this, CiPriority.Statement);
Write(')');
```

The main challenges would be
* Extracting a function needs to automatically add something to the function name if it would conflict with the user's own identifiers
* Since generation relies on sequential `Write` calls there's not currently a way to go back and insert something at the top of the output

What do you think?  If nothing else we could run all the code through a visitor to decide what to extract before writing anything.

**Comment by pfusik** [comment]
There's a mechanism for that. Search for `GenJsMethod`.

**Comment by jedwards1211** [comment]
Oh okay, great!
