### ISSUE TITLE
C target returns pointer to freed memory

### ISSUE THREAD

**Issue by machado2** [pfusik/cito#22]
I was curious how it deals with strings when targeting pure C, so I tested with:

	protected string Batata!() {
		string name = "John";
		int born = 1979;
		int now = 2019;
		string() s = $"{name} is {now - born} years old";
		return s;
	}

And it compiled to:

    static const char *ImageDecoder_Batata(ImageDecoder *self)
    {
        const char *name = "John";
        int born = 1979;
	    int now = 2019;
	    char *s = CiString_Format("%s is %d years old", name, now - born);
	    const char *returnValue = s;
	    free(s);
	    return returnValue;
    }

returnValue is a pointer to s that was just freed

**Comment by pfusik** [comment]
Your code is invalid. It returns a reference to a local string storage. You can make the very same error in C by returning a pointer to a variable local to the function.
What you want is to return string _storage_:

    public string() Batata!()

Yes, this should be signalled as an error by `cito`. I think that diagnostics are its weakest point.
