### ISSUE TITLE
How to use existing C struct as a base?

### ISSUE THREAD

**Issue by psprint** [pfusik/cito#23]
I'm writing Midnight Commander fork. I thought that I could use cito to make it easier and cleaner. However, how could I use an existing C struct, like WDialog, as a base of a new class? In general, how to include the headers of existing C project?

**Comment by pfusik** [comment]
I don't quite understand what you're trying to achieve. What languages do you want to target?

**Comment by psprint** [comment]
I would like to develop a C project with Cito. Ie. to write further code in
Cito. For this I need to be able to extend existing OOP style structs.

czw., 17 cze 2021, 18:07 użytkownik Piotr Fusik ***@***.***>
napisał:

**Comment by pfusik** [comment]
If your project is entirely in C, why use Ć and not C?

**Comment by psprint** [comment]
To have nice OOP syntax, not an emulated one.

pt., 18 cze 2021, 16:59 użytkownik Piotr Fusik ***@***.***>
napisał:

**Comment by pfusik** [comment]
Ć wasn't designed as an OOP extension of C. `cito` doesn't understand C code, in particular header files.
