### ISSUE TITLE
SortedDictionary failed

### ISSUE THREAD

**Issue by ali-ramezani** [pfusik/cito#25]
I like the work you have done and really appealing.
As it is mentioned in your tester and I also tested with your mentioned example for `foreach` the code fail to generate and shows internal C# messages which is misleading.
- I think in first phase bypass this by showing proper error like line X: SortedDictionary is not supported yet
- Try to support
I will spend more time and if I had time I would fix it to have a little contribute

**Comment by pfusik** [comment]
Thank you for reporting this!

Implementing proper error messages for features not supported by particular backends is my top priority.

Are you particularly interested in this test or some specific backend? `StForeachSortedDictionary` only fails on OpenCL, or if you compile with an old `glib` or .NET.

**Comment by pfusik** [comment]
There were about 50 `cito` failures when running all the tests. Fixed all.
