### ISSUE TITLE
Read-only/read-write references induce dangling pointers in C and C++?

### ISSUE THREAD

**Issue by yeputons** [pfusik/cito#28]
I believe that "reference" in the docs is used in Java/C# sense, not in C++ sense: you can use them with no fear of accessing deleted object.

Consider the following code (feel free to close it if it's incorrect):

```
class Foo {
	int data;
	Foo ref;
}
public static class Test
{
	public static void Run()
	{
		Foo# a = new Foo();
		{
			Foo# b = new Foo();
			a.ref = b;
		}  // (!)
		Console.Write(a.ref.data);
	}
}
```

it gets compiled to the following C++ code:

```
class Foo
{
public:
	Foo() = default;
private:
	int data;
	const Foo * ref;
};

void Test::run()
{
	std::shared_ptr<Foo> a = std::make_shared<Foo>();
	{
		std::shared_ptr<Foo> b = std::make_shared<Foo>();
		a->ref = b.get();
	}
	std::cout << a->ref->data;
}
```

and the following C code:

```
struct Foo {
	int data;
	const Foo *ref;
};

void Test_Run(void)
{
	Foo *a = (Foo *) CiShared_Make(1, sizeof(Foo), NULL, NULL);
	{
		Foo *b = (Foo *) CiShared_Make(1, sizeof(Foo), NULL, NULL);
		a->ref = b;
		CiShared_Release(b);
	}
	printf("%d", a->ref->data);
	CiShared_Release(a);
}
```

In both cases, `Foo *b` is destroyed at the `(!)` mark and `a.ref.data` now points to a destroyed object, so it is undefined behavior. Java version works as expected: `b` is preserved until it's no longer used.

So it looks like there are very different semantics for read-only references in different output languages. Unfortunately, there is no way to fully solve this problem without writing your own garbage collector for C and C++ as there may be cyclic references.

However, if cyclic references are prohibited, making read-only references counted should help. I believe similar problem exists with read-write object references.

**Comment by pfusik** [comment]
The language reference already said this:

> It is an error to use a reference pointing at an array or object outside of its scope.

but now I added more warnings about dangling references.

Thanks!
