### ISSUE TITLE
[Language request] Please add D programmimng language

### ISSUE THREAD

**Issue by Teashrock** [pfusik/cito#34]
D programming language is a low-level C++ rework with very convenient syntax, very fast compilation results, and clearly understandable code. It has the main features of C++, but they work in their own, programmer-friendly way.
One can read about it here: https://dlang.org
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/D_Programming_Language_logo.svg/1280px-D_Programming_Language_logo.svg.png)

**Comment by pfusik** [comment]
cito used to have a D backend created by @epi. I expect that restoring it would be straightforward now that we have a testsuite.

**Comment by pfusik** [comment]
Please stay on topic. This is a reasonable request for a new backend. We have the Java backend already.

I owe you an explanation why there's no D backend at the moment. A few years ago cito underwent a complete rewrite to address language changes and better error reporting. Every backend requires some work and I chose to postpone the D backend.

I'd be happy to accept a pull request with a well-written `GenD.cs`. I can offer help implementing that. If you have experience with D, you can start by looking at how the other backends are implemented.
