### ISSUE TITLE
Printing concatenated results

### ISSUE THREAD

**Issue by JoshuaWierenga** [pfusik/cito#36]
Are there any plans for more general concatenation support when going to languages without proper support like c? 
This came up while trying Console.Write as `Console.Write(int + string)` gives `fputs(int + string, stdout)` and so relies on c to handle it which of course it won't do. This doesn't happen when the int and string are printed separately as `Console.Write(int)` will correctly give `printf("%d", int)`. Is printing different types separately just the intended way or is this a bug? 

Provided this is reasonable to fix, `printf(%d%s, int, string)` should work fine and generalise to other combinations but I haven't checked what the support for format strings is like since most of the supported languages don't even have them.

**Comment by danon** [comment]
@pfusik Is this still an issue in 2023?
