### ISSUE TITLE
Simple build script

### ISSUE THREAD

**Issue by mingodad** [pfusik/cito#49]
Trying to build this project on Linux I get this error message:
```
make
dotnet build
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'build' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
Makefile:38: recipe for target 'cito.exe' failed
make: *** [cito.exe] Error 145
```
But using the simple shell script shown bellow it builds fine, I suggest add it or something like it as alternative build system (also could be a batch file for windows).
```
csc /out:Cito.exe /t:exe \
	AssemblyInfo.cs \
	CiDocLexer.cs \
	CiDocParser.cs \
	CiException.cs \
	CiLexer.cs \
	CiParser.cs \
	CiResolver.cs \
	CiTo.cs \
	CiTree.cs \
	GenBase.cs \
	GenCCpp.cs \
	GenC.cs \
	GenCl.cs \
	GenCpp.cs \
	GenCs.cs \
	GenJava.cs \
	GenJs.cs \
	GenPy.cs \
	GenPySwift.cs \
	GenSwift.cs \
	GenTs.cs \
	GenTyped.cs
```

**Comment by pfusik** [comment]
What is your setup:
- Which .NET SDK do you have? 
- Which package does `csc` come from?

**Comment by mingodad** [comment]
I only have this on my `/etc/apt/sources.list.d/mono-official-vs.list`
```
deb https://download.mono-project.com/repo/ubuntu vs-bionic main
```

**Comment by pfusik** [comment]
Last time I checked Mono couldn't build `cito` because of no support for new C#. I will re-check it and enable Mono as an alternative build system. Mono is already used for the C# backend tests on Linux.

**Comment by pfusik** [comment]
Mono's `csc` is `Microsoft (R) Visual C# Compiler`. The other Mono's compilers don't handle modern C#.

You can simply build using .NET SDK. That works on Windows/macOS/Linux.
