### ISSUE TITLE
Maybe you can use LLVM?

### ISSUE THREAD

**Issue by Danon** [pfusik/cito#51]
Have you tried compiling your language to LLVM?

In short, you know how you can compile Java/Kotlin/Scala to JVM byte cote, and it takes care of every architecture?

You can do the same with Cito; if you compile the program into LLVM byte code - you can run the program on any architecutre (86/64, and any OS).

**Comment by Danon** [comment]
There is even instruction how to write your own compiler to your own langauge (which you already have): https://llvm.org/docs/tutorial/

It's not easy, but you could run programs in cito without transpiling them first. Pretty cool, huh? :D And LLVM would handle all the architecture headache away.

**Comment by pfusik** [comment]
Thank you for your question!

Cito has different goals than LLVM.
LLVM emits *optimized machine code* for C and C++.
Cito emits several *readable, reusable code* in several high-level languages that is as close to the source as possible.
I don't see how using LLVM would help.

**Comment by Danon** [comment]
It would allow you to compile a program written in Cito to a lightweight executable.

Some of your users may want to just write program in Ć and then run it, without transpiling to other lanagues.
