### ISSUE TITLE
Keyword mut instead opposite keyword const

### ISSUE THREAD

**Issue by borneq** [pfusik/cito#55]
For concurrency preferable are immutable fields, these should be default, only mutable will have keyword mut. In Pony concurrency model, immutable fields can be fine shared between actors, only mutable require asynchronous messages.

**Comment by pfusik** [comment]
Do you mean [this Pony](https://www.ponylang.io)?
A design goal of Ć is _obvious_ translation to the target languages. In all the target languages fields are mutable. Making them immutable would make Ć much harder to use by the users of the target languages.
`const` in Ć means "compile-time constant", same as in C#. This is different from C/C++ `const` meaning "immutable".
