### ISSUE TITLE
Add C language macro

### ISSUE THREAD

**Issue by ChinaQes** [pfusik/cito#67]
Used to reduce boilerplate code

**Comment by pfusik** [comment]
What do you mean?

**Comment by Mart-Bogdan** [comment]
I believe @ChinaQes means to add macros similar to ones existing in C to this language. With #define keyword, or similar.

**Comment by Mart-Bogdan** [comment]
I would add that it would be nice to have `#ifdef`  analogue. 
It can be useful, for example, to plant code specific for target into block like

```c
#ifdef JAVA
// some Java specific code
#endif
```

Perhaps this can be put into separate issue, as macros itself are more complex.

Disclaimer. I am sorry, but I am not aware if such feature already exists, because I am new to this project, just saw it. I beg pardon, if it already exist.

**Comment by pfusik** [comment]
Initial versions used to have C-style macros. Now I think the language is better without them.

[Conditional compilation](https://github.com/pfusik/cito/blob/master/ci.md#conditional-compilation) does exist, with syntax identical to C#. Symbols either exist or not, they have no value. Example:

```csharp
#if JAVA
// some Java specific code
#endif
```

Use `-D symbol`  to define a symbol on the command line:

    cito -o Foo.java -D JAVA Foo.ci

**Comment by Mart-Bogdan** [comment]
Thanks for info. Good that it exists.

**Comment by KFKMan** [comment]
Can we define macro variables? If not, can you add support?

For example;
```
#define VariableType int

public static class Example
{
       public static VariableType Sum(VariableType a, VariableType b){
              return a + b;
       }
}
```

**Comment by pfusik** [comment]
What's a real-world scenario where this would be useful? Your example is simpler by saying `int` instead of `VariableType`.

I'm not going to add a C-style preprocessor, but nothing stops you from invoking a C preprocessor from your build system and passing the output to fut.
