### ISSUE TITLE
Provide examples of generated code

### ISSUE THREAD

**Issue by Mart-Bogdan** [pfusik/cito#68]
Please provide in source tree directory with output of readme example. Ideally include in that dir some other sample code files as well.

**Comment by pfusik** [comment]
Do you mean something like [this](https://github.com/pfusik/qoi-ci/tree/master/transpiled) ? For real-world samples, see #21.

**Comment by Mart-Bogdan** [comment]
Yes. But would be nice to have it in current repo, and with easier example.

**Comment by pfusik** [comment]
https://github.com/pfusik/cito/blob/master/doc/getting-started.md includes a minimal example. Is that ok?
