### ISSUE TITLE
NaN/Infinite values

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#7]
I don't see constants for NaN/Infinity in the language reference, are they supported yet?

**Comment by pfusik** [comment]
Added now. Thanks!

**Comment by jedwards1211** [comment]
Oh that was fast, thanks!  But so fast I forgot to also mention `Math.isNaN`/`Math.isInfinite`/`Math.isFinite` 😅  (isFinite meaning not NaN or infinite in languages I'm aware of)

**Comment by pfusik** [comment]
Done.

**Comment by jedwards1211** [comment]
Very cool, thanks!
