### ISSUE TITLE
Comments resulting with &gt; and %:lt; strings.

### ISSUE THREAD

**Issue by urosjarc** [pfusik/cito#72]
For the following languages, docs comments do not result in the correct format: c, cpp, cs, java, js, ts.
For python the docs are correct.

## SOURCE
```
    /// <summary>
    /// Pretvori šteilko v osmiški zapis.
    /// </summary>
    /// <param name="a">Cela številka v desetiškem zapisu.</param>
    /// <returns>Cela številka v osmiškem zapisu.</returns>
```

## c
```
/**
 * &lt;summary&gt;
 * Pretvori šteilko v osmiški zapis.
 * &lt;/summary&gt;
 * &lt;param name="a"&gt;Cela številka v desetiškem zapisu.&lt;/param&gt;
 * &lt;returns&gt;Cela številka v osmiškem zapisu.&lt;/returns&gt;
 */
```

## cpp
```
	/**
	 * &lt;summary&gt;
	 * Pretvori šteilko v osmiški zapis.
	 * &lt;/summary&gt;
	 * &lt;param name="a"&gt;Cela številka v desetiškem zapisu.&lt;/param&gt;
	 * &lt;returns&gt;Cela številka v osmiškem zapisu.&lt;/returns&gt;
	 */
```

## cs
```
	/// <summary>&lt;summary&gt;
	/// Pretvori šteilko v osmiški zapis.</summary>
	/// <remarks>&lt;/summary&gt;
	/// &lt;param name="a"&gt;Cela številka v desetiškem zapisu.&lt;/param&gt;
	/// &lt;returns&gt;Cela številka v osmiškem zapisu.&lt;/returns&gt;</remarks>
```

## java
```
	/**
	 * &lt;summary&gt;
	 * Pretvori šteilko v osmiški zapis.
	 * &lt;/summary&gt;
	 * &lt;param name="a"&gt;Cela številka v desetiškem zapisu.&lt;/param&gt;
	 * &lt;returns&gt;Cela številka v osmiškem zapisu.&lt;/returns&gt;
	 */
```

## js
```
/**
 * &lt;summary&gt;
 * Pretvori šteilko v osmiški zapis.
 * &lt;/summary&gt;
 * &lt;param name="a"&gt;Cela številka v desetiškem zapisu.&lt;/param&gt;
 * &lt;returns&gt;Cela številka v osmiškem zapisu.&lt;/returns&gt;
 */
```

## python
```
		"""<summary>
		Pretvori šteilko v osmiški zapis.

		</summary>
		<param name="a">Cela številka v desetiškem zapisu.</param>
		<returns>Cela številka v osmiškem zapisu.</returns>"""
```

## ts
```
	/**
	 * &lt;summary&gt;
	 * Pretvori šteilko v osmiški zapis.
	 * &lt;/summary&gt;
	 * &lt;param name="a"&gt;Cela številka v desetiškem zapisu.&lt;/param&gt;
	 * &lt;returns&gt;Cela številka v osmiškem zapisu.&lt;/returns&gt;
	 */
```

**Comment by pfusik** [comment]
This is expected. You are using C# syntax of XML tags in documentation comments. Use [Ć syntax for documentation comments](https://github.com/pfusik/cito/blob/master/ci.md#documentation-comments) instead.

**Comment by urosjarc** [comment]
Can you reopen this issue, I'm interested to fixing this in pull request because it seems a simple fix. Maybe if I could make it so that docs comments result in official docs comments for every language like JSDocs, [Doxygen](https://doxygen.nl/) etc...

**Comment by pfusik** [comment]
What would you like to fix here? If you type `<` in a Ć doc comment, it means you want to see `<` in the generated documentation and therefore it needs to be escaped in C#, Java and Doxygen syntax.

**Comment by urosjarc** [comment]
Ooooooohhhhhhh I see now what you did there, thank you for clarification, I didn't found this in the docs.

**Comment by urosjarc** [comment]
Does this works for returning tag? [<return>](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#d313-returns)

**Comment by pfusik** [comment]
There is no support for the `<returns>` tag. I'd love to have it added! That could be your first PR. Note that:

1. It should be supported for all the target languages, not just C#.
2. I'd prefer lightweight Markdown style and not some XML or JavaDoc tags. How about a doc comment line starting with the "Returns" word?
