### ISSUE TITLE
License of generated code?

### ISSUE THREAD

**Issue by MK-Alias** [pfusik/cito#77]
Goodday,

I've just started to play with Ć and i'm wondering if there is a license of the generated code? Or can everybody just license the code as we wish?

Thanks in advanced for any help on this.

**Comment by pfusik** [comment]
Thank you for your question!

`cito` itself is on GPL 3 (https://github.com/pfusik/cito/blob/master/COPYING), but this in _no way_ affects the transpiled code it outputs.
This is similar to GCC being on the GPL, but the code emitted by GCC is not on GPL. In fact, a lot of commercial software, on all kinds of licenses, is built with GCC.

**Comment by MK-Alias** [comment]
Thanks for your quick reply!

The runtime of GCC has an explicit license (see: https://www.gnu.org/licenses/gcc-exception-3.1.html) that protects the runtime from the GPL restrictions. Because they understand that you need some flexibility in this matter. However, most languages have a "default-runtime", and lots of them are licensed.

So a better question is: does cito have/embeds a default-runtime of sorts that has a license?

Judging from your first response it is probably no, but still want to be explicit!

Ć looks like a great tool/langauge and I want to dig into it. So i hope that its usable for any type of programming, just like gcc.

Thanks for your time, and feel free to close the ticked after your next reply!

**Comment by pfusik** [comment]
`cito` emits very little code that could be considered a runtime library. These are mostly trivial implementations of string and shared pointer handling in C, and only the parts used by your code are emitted. I never meant to license them.

Thanks for pointing out the GCC RTL Exception. Perhaps I will adopt it.
