### ISSUE TITLE
returning readonly reference

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#8]
I've got this method (want to use an immutable object pattern, not concerned about max performance):

```c#
  public static Length Create(double value, LengthUnit unit) {
    Length length = new Length();
    length.Set(value, unit);
    return length;
  }
```
I think this output C++ code leaks memory?  I'm not an expert in C++ but I don't see a way that the shared pointer could be released:
```cpp
const Length * Length::create(double value, LengthUnit unit)
{
	const Length * length = std::make_shared<Length>().get();
	length->set(value, unit);
	return length;
}
```

**Comment by pfusik** [comment]
This should be:

```csharp
public static Length# Create(double value, LengthUnit unit) {
    Length# length = new Length();
    length.Set(value, unit);
    return length;
}
```

Diagnostics need to be improved - assigning a new object to a non-shared pointer is obviously a leak.

**Comment by pfusik** [comment]
Error added - it catches cases such as:

```csharp
Length p = new Length();
Length Create() { return new Length(); }
void Foo(Length length) { } ... Foo(new Length);
```

with the message:

    ERROR: Dynamically allocated object must be assigned to a Length# reference

**Comment by jedwards1211** [comment]
Thanks!  Yeah I understand `Length#` works, as stated in another issue I'm wanting to use an immutable class pattern and wish I could get a simpler C++ API for it.
