### ISSUE TITLE
Transpiled.cs not reproducible

### ISSUE THREAD

**Issue by Chuvi-w** [pfusik/cito#85]
1. `rm Transpiled.cs to force it rebuild`
2. `make`
3. multiple errors, like `GenJs.ci(942): ERROR: Expected ':', got 'when'` appears.

A new case syntax is coming?

UPD:
Well, seems I've managed to rebuild it manually.
1. Create Transpiled.cs without GenJs.ci, GenTs.ci and  GenSwift.ci.
2. Remove them from CiTo::Emit
3. build cito.
4. Create full Transpiled.cs with new cito
5. Restore CiTo::Emit
6. build full cito again.

**Comment by pfusik** [comment]
1. Build `cito` using `Transpiled.cs`.
2. Put it on your PATH.
3. Use it for building `cito`.
