### ISSUE TITLE
[Feature Request] [with suggestion] add `make install` target.

### ISSUE THREAD

**Issue by dreirund** [pfusik/cito#86]
Ahoj,

to ease packaging for Unix systems, please add a `make install` target, which installs everything to run `cito` system-wide to the appropriate directories, and which honours `DESTDIR`:

* By default, install to a directory structure under `/usr/local/`,
* if `DESTDIR=/somedirectory` is specified, install to a proper directory structure under `$(DESTDIR)/`.  
  (e.g. executable to `usr/bin/cito`, if shared libraries belong to the project they go into `usr/lib/`, documentation into `usr/share/doc/cito`, etc.)

My solution was to

1. copy `<cito-build-directory>/bin/Debug/net*/*` into `$DESTDIR/usr/lib/cito/`,
2. `chmod 755 $DESTDIR/usr/lib/cito/cito`,
3. `ln -s $DESTDIR/usr/lib/cito/cito $DESTDIR/usr/bin/cito`.

(See [&nearr;&hairsp;this `PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cito-git).

I don't know if this is sufficient.

Also, I do not want to have a debug build, but that was the only think which was produced.

Regards!

**Comment by pfusik** [comment]
Thanks for reporting this!

Now that `cito` is ported to Ć (#48), one can build it transpiled to C++. To solve the chicken-and-egg problem, `Transpiled.cpp` is checked into Git, so the only build dependency is a C++20 compiler, such as gcc 13 or clang 16.

`make install` will install the C++ binary. I will add the man page later. Not sure if installing `*.md` docs and `/usr/share/licenses/cito/COPYING` is recommended on all Linux distros?
