### ISSUE TITLE
Use PLOOC for OOP on C?

### ISSUE THREAD

**Issue by ghost** [pfusik/cito#90]
https://github.com/GorgonMeducer/PLOOC

**Comment by iahunq** [comment]
@pfusik Should this issue be closed as not planned?

**Comment by pfusik** [comment]
It seems that PLOOC provides no added value to `cito` and only a drawback of an added dependency.

I'm not familiar with PLOOC, but looking at the README:

> Provide protection for private class members
> Support protected members

`cito` does not expose `struct` fields in the header file. Objects are allocated on the heap using the emitted `New`/`Delete` functions.

> Support multiple inheritance

Ć does not support multiple inheritance.

> Support interface implementation

Ć does not support interfaces.

> Support strict type checking/validation in certain compilers, such as IAR with multi-file compilation enabled.

Not sure what exactly is meant here. `cito` output is a standards-conforming, type-safe C.

> Compliant with ANSI-C99

So is `cito` output.

> ANSI-C90 is also supported but the protection for private feature is disabled.

Ć no longer supports C90.

> Support Overload

Ć does not support overloading.
