### ISSUE TITLE
Use something other than glib

### ISSUE THREAD

**Issue by ghost** [pfusik/cito#91]
Reasons: https://suckless.org/sucks/

List of alternatives:

https://github.com/oz123/awesome-c#data-structures

https://github.com/oz123/awesome-c#frameworks

**Comment by pfusik** [comment]
https://suckless.org/sucks/ lists three "alternatives" to glib, each one less popular than `cito`, and neither seems to implement a resizable array or regular expressions.

From your lists of alternatives, I only heard about APR before.

**Comment by iahung** [comment]
Because traditional alternatives to glib are too limited people come up with many newer solutions, especially embedded people as glib is clearly not suitable for embedded. Please have a look at TBOX.

p/s: I don't suggest you to choose TBOX, it only served as an example to show how capable modern alternatives to glib are.

**Comment by pfusik** [comment]
TBOX looks promising. One problem I see is no `SortedDictionary` / `std::map` / `GTree` equivalent.

**Comment by iahung** [comment]
You could submit an issue asking the developer to add it:

https://github.com/tboox/tbox

**Comment by iahunq** [comment]
@pfusik Should this issue be closed as not planned?

**Comment by pfusik** [comment]
Yes, I see no reason to provide an alternative to `glib` in near future.

**Comment by iahung2** [comment]
> Yes, I see no reason to provide an alternative to `glib` in near future.

I think this is an legitimate concern. Please reopen this issue. You don't have to remove support for GLib. Both GLib and TBOX should be available as backends when transpiling to C. Perhaps you should add a new switch for that.

**Comment by iahung2** [comment]
> List of alternatives:
> 
> https://github.com/oz123/awesome-c#data-structures
> 
> https://github.com/oz123/awesome-c#frameworks

There are many libraries freely available for you to pick up. You don't have to choose TBOX.

**Comment by pfusik** [comment]
Why evaluate alternatives? What's wrong with glib?

**Comment by iahung2** [comment]
> Why evaluate alternatives? What's wrong with glib?

`glib` aborts in out-of-memory situations. Please read https://suckless.org/sucks/ again.

**Comment by pfusik** [comment]
> glib aborts in out-of-memory situations.

Like most of all software. If your program uses 10 GB of RAM, how do you think it can work when there's no 10 GB of RAM available?
